#==================================================================
# GitHub Pages Configuration
#==================================================================

title: "GCET231 Tutorial 4: Criando um Projeto no Quartus Prime"
